export const categoriess = [
  { name: "Электроника", path: "productsByType" },
  { name: "Бытовая техника", path: "productCategories" },
  { name: "Одежда", path: "AllProducts" },
  { name: "Аксессуары", path: "productsByType" },
  { name: "Красота и уход", path: "productsByType" },
  { name: "Здоровье", path: "productsByType" },
  { name: "Товары для дома", path: "productsByType" },
  { name: "Строительство и ремонт", path: "productsByType" },
  { name: "Автотовары", path: "productsByType" },
  { name: "Детские товары", path: "productsByType" },
  { name: "Хобби и творчество", path: "productsByType" },
  { name: "Спорт и отдых", path: "productsByType" },
  { name: "Продукты питания", path: "productsByType" },
  { name: "Бытовая химия", path: "productsByType" },
  { name: "Канцтовары", path: "productsByType" },
  { name: "Книги", path: "productsByType" },
  { name: "Дача, сад и огород", path: "productsByType" },
  { name: "Субсидируемые товары для реабилитации", path: "productsByType" },
];
